### ISSUE TITLE
error '62' with EOF

### ISSUE THREAD

**Issue by hiddenllyy** [hiddenllyy/Internship-with-VBA#6]
I've met a new problem...
With the new xlsm. named TEXT_VBA.
the loop of Whole Not EOF(1) is blocked at the end of the circle. It can show me the first file's name and his contents. But it can not open the second file. 
I've searched the reason, the answer is zhen we chose Binary mode, the EOF can not figure the end. And It's recommanded to use Loc or Seek function. but I chose the mode as Input, and the Loc doesn't seem to work in this cas, so i don't know how to do that.

**Comment by mincong-h** [comment]
Not sure how to fix this problem, but using _**Input**_ mode should not be a good idea since nothing is going to be written to it. You just need to read the data from `.txt` files, so _**Output**_ might be a good idea. According to the syntax provided by MSDN : 

> Open pathname For mode [Access access] [lock] As [#]filenumber [Len=reclength]

You can try the below code.

``` vba
' pathname = fichOpen
' mode = Output
' Access = Read
' lock = Lock Read (not sure, might cause problem to robot programs)
' filenumber = 1
Open fichOpen For Output Read Lock Read As #1
```

**Comment by hiddenllyy** [comment]
Does the xlsm work when you tested this code (the message box shows up and give you the content in the text)? Cause it suddenly doesn't work... AHHHHH I am tired with that...

**Comment by mincong-h** [comment]
We can get tired very soon when we meet bug without finding the solution. But that's why it is interesting to learn more and avoid this situation. Of course, this situation is caused some how by Microsoft. In visual basic, error messages are really difficult to understand. But you see, I'm still here and try to help you. So just don't give up :smiley: 

Are you testing your file `brouillon.xlsm`, and meeting the following error ?

>   Run-time error '424', object required

If yes, that is because your `FileSystemObject` is empty. You can not used an object before initialization (object required).

> But how can you know it is empty ? 

Check your window **Locals**:

![issue-6-vba-window-locals](https://cloud.githubusercontent.com/assets/10179217/15473779/0561424c-2102-11e6-884c-ac416ad38d7a.PNG)

However, you didn't use `FileSystemObject` correctly. The example code had already given in issue #3 via the link to Stack Overflow. Did you try [that](http://stackoverflow.com/questions/17671725/application-filesearch-in-excel-2007-w-loop) ?

**Comment by hiddenllyy** [comment]
Thank you for your courage words! I've leart another skill!😃I'll try that
when I arrive home.😄Thanks again! And see you later!
2016年5月23日 16:24，"Mincong HUANG" notifications@github.com写道：

We can get tired very soon when we meet bug without finding the solution.
But that's why it is interesting to learn more and avoid this situation. Of
course, this situation is caused some how by Microsoft. In visual basic,
error messages are really difficult to understand. But you see, I'm still
here and try to help you. So just don't give up 😃

Are you testing your file brouillon.xlsm, and meeting the following error ?

Run-time error '424', object required

If yes, that is because your FileSystemObject is empty. You can not used an
object before initialization (object required).

But how can you know it is empty ?

Check your window _Locals_:

[image: issue-6-vba-window-locals]
https://cloud.githubusercontent.com/assets/10179217/15473779/0561424c-2102-11e6-884c-ac416ad38d7a.PNG

However, you didn't use FileSystemObject correctly. The example code had
already given in issue #3
https://github.com/hiddenllyy/Internship-with-VBA/issues/3 via the link
to Stack Overflow. Did you try that
http://stackoverflow.com/questions/17671725/application-filesearch-in-excel-2007-w-loop
?

**Comment by mincong-h** [comment]
You're welcome, just keep going. I know that you can handle it. 💪

**Comment by hiddenllyy** [comment]
Good aftrnoon Mincong, 
Today this code works, but it's weird because it shows nothing. The msgbox showed me the concents yesterday but now it seems that the cycle of Do While doesn't run as usual. 
Could you please check this and L'm afraid that this afternoon I can not do much things cause I have 2 meetings to attend. It's unormal for a trainee to attend so much meetings... (0.0)
Have a good day and see you later,

**Comment by hiddenllyy** [comment]
I don't know if this concerns the function EOF, so I leave it opened, if you think it's another problem you may close it and reopen a new one.

**Comment by mincong-h** [comment]
Hi @hiddenllyy ,

Glad to hear that the code works :smile: . Busy is good thing, it means that you're important ! Each Tuesday, I need to prepare taining lesson for my collegues for the next day, so I won't have time to look at it until tonight. I can't close issues because I'm not repository owner or trusted contributor.

**Comment by hiddenllyy** [comment]
No it doesn't matter! Take your time and just check my code when you are free.
first of all, how can I change you into myu trusted contributor? So that you can more participate into my  repositories I think?
And could you explain how does this code works please? I find it on the internet for checking the 'mot-clé' but I don't all understand it.
`Private Sub CommandButton1_Click() 
    str1 = Sheets(1).Range("b1").Value 
    str2 = Sheets(1).Range("b2").Value 
    Sheets(1).Range("b3").Value = InStr(1, str1, str2) 
    Sheets(1).Range("b4").Value = InStr(1, str1, str2) >= 1 
End Sub`
The contributor doesn't give more explainations or examples but I think it will be helpful for my project.

**Comment by mincong-h** [comment]
> how can I change you into my trusted contributor?

You can add me by:
1. Clicking here : https://github.com/hiddenllyy/Internship-with-VBA/settings
2. Choose the _collaborators_ option on the left navigation bar
3. Confirm your password
4. Find me name @mincong-h and add it.

> InStr Function 

``` vba
Private Sub CommandButton1_Click()
   str1 = Sheets(1).Range("b1").Value
   str2 = Sheets(1).Range("b2").Value
   Sheets(1).Range("b3").Value = InStr(1, str1, str2)
   Sheets(1).Range("b4").Value = InStr(1, str1, str2) >= 1
End Sub
```

First of all, you should take a look at the official documentation : [MSDN | InStr Function (Visual Basic)](https://msdn.microsoft.com/en-us/library/8460tsh1.aspx). Always official document first !!

In order to explain the code, I'll use an example : assume that cell **B1**'s value is `Hello VBA` and **B2**'s value is `Hello`:

|  | A | B |
| --- | --- | --- |
| 1 |  | hello VBA |
| 2 |  | hello |

``` vba
Private Sub CommandButton1_Click()

   ' hello VBA
   str1 = Sheets(1).Range("b1").Value

   ' hello
   str2 = Sheets(1).Range("b2").Value

   ' starting from the 1st character of str1 "Hello VBA"
   ' and try to find out whether str2 "Hello" is in this string
   ' then returns an integer specifying the start position of 
   ' the first occurrence of str2 within str1.
   ' in my example, "Hello" occurs in the 1st position of the 
   ' string "Hello VBA", so the returned value is 1
   ' so cell b3 equals to 1
   Sheets(1).Range("b3").Value = InStr(1, str1, str2)

   ' here's a little bit different :
   ' 1 is always the value returned by the function InStr(1, str1, str2)
   ' but the next step is to do comparison:
   ' is (1 >= 1) ?
   ' that is true
   ' so the comparison returns TRUE
   ' so cell b4 equals to TRUE
   Sheets(1).Range("b4").Value = InStr(1, str1, str2) >= 1

End Sub
```

**Comment by mincong-h** [comment]
## Code review

However, as you can see, this code is not written very clearly. So we can do a code review on it : 
1.  We can change the sub name to show to usage of the sub, let's say `FindKeyword`.
2.  String variables' names are difficult to understand, `str1` and `str2` are not very helpful for understanding the context. What about using `SearchString` for the target search string and `keyword` for the second one ? That's more meaningful
3.  The 1st parameter about position is optional: by default, it is 1. So no need to write it anymore
4.  We don't know what is returning, neither `InStr(1, str1, str2)` and `InStr(1, str1, str2) >= 1`. So it is better to create more variables to give sens to this returned values. For the first one, since the function returns the keyword position, what about naming `keywordPosition` or `keywordPos` ? The second should be difficult to understand, add `()` might be better, we know then it returns either _YES_ or _NO_.

The final code looks like : 

``` vba
Private Sub FindKeyword()
    searchString = Sheets(1).Range("b1").Value
    keyword = Sheets(1).Range("b2").Value
    keywordPosition = InStr(searchString, keyword)
    Sheets(1).Range("b3").Value = keywordPosition
    Sheets(1).Range("b4").Value = (keywordPosition >= 1)
End Sub
```

**Comment by mincong-h** [comment]
I'm running out of time. I must leave now. Hope the above comments help you, not only for this temporary issue, but in a greater scope : about how the learn software engineering and write good quality code. These are very important points. See you.

**Comment by mincong-h** [comment]
BTW, you should take a look about [Basic writing and formatting syntax](https://help.github.com/articles/basic-writing-and-formatting-syntax/) in markdown. These comments support markdown syntax.

**Comment by mincong-h** [comment]
Hi @hiddenllyy, I tried to understand your code but there're too many things. I suggest you to : 
1.  Open a new issue for the `EOF` question
2.  Clean up your current code by cutting them in different subs. Here's an example : 
   
   ``` vba
   Sub Main()
       Dim msg As String
       msg = "Hello world"
       ' call a sub here
       ShowMessage msg
       ' call a funtion here
       Debug.Print CompareStr(msg, "Hello world")
   End Sub
   
   Sub ShowMessage(msg As String)
       Debug.Print msg & " from Sub ShowMessage()"
   End Sub
   
   Function CompareStr(str1 As String, str2 As String) As Boolean
       CompareStr = (str1 = str2)
   End Function
   ```
   
   And the results shown in window _Immediate_ : 
   
   ```
   Hello world from Sub ShowMessage()
   True
   ```
